//
// Created by se00598 on 01/11/23.
//

#ifndef MANGOSTEEN_INSTRUMENTATION_TRANSIENT_ALLOCATOR_H
#define MANGOSTEEN_INSTRUMENTATION_TRANSIENT_ALLOCATOR_H

#endif //MANGOSTEEN_INSTRUMENTATION_TRANSIENT_ALLOCATOR_H
