//
// Created by se00598 on 08/09/23.
//

#ifndef MANGOSTEEN_INSTRUMENTATION_CONFIGURATION_H
#define MANGOSTEEN_INSTRUMENTATION_CONFIGURATION_H

#include "../state.h"

#define LOG_TO_RING_BUFFER
//#define DISABLE_CONSUMER_AFTER_RECOVERY
//#define RADIX_SORT
//#define DISABLE_INSTRUMENTATION_AFTER_RECOVERY
//#define EXECUTE_RO_TRANSACTIONALLY
//#define CONSUMER_SKIP_REDO
//#define CONSUMER_SKIP_MMAP
//#define TEST_WITHOUT_BACKEND
//#define RUN_WITHOUT_CPU_SET
#define RUN_WITHOUT_INSTRUMENTATION
#define SKIP_CHECKPOINT
#define RUN_WITHOUT_BACK_END //tryingthis one
//#define DEBUG_FLAT_COMBINING
//#define SPLIT_ALLOCATOR
//#define DEBUG 1
//#define DEBUG_MANGOSTEEN_MAIN
//#define DEBUG_INSTRUMENTATION
//#define DEBUG_REGION_TABLE
//#define DEBUG_RING_BUFFER
//#define ENABLE_PROFILING
//#define STACK_FILTERING
#ifdef __cplusplus

#endif
#define DISABLE_OVERFLOW_BUFFER
//#define USE_PER_BATCH_MEMORY_MMAPING_SYNCRONIZATION
#define EPOLL_SERVER
#define HASH_SET_SIZE 2048
#define PAYLOAD_SIZE 32
#define USE_DEDUPLICATION_BUFFER
//#define RPC_MODE 0
#endif //MANGOSTEEN_INSTRUMENTATION_CONFIGURATION_H
